name: Release Helm Charts with Changelog

on:
  push:
    branches:
      - main
      - CX-4.10.4
      - CX-5.0-alpha
    paths:
      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout full git history
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -----------------------------
      # Configure Git identity
      # -----------------------------
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # -----------------------------
      # Install Helm
      # -----------------------------
      - name: Install Helm
        uses: azure/setup-helm@v3

      # -----------------------------
      # Add Helm repositories
      # -----------------------------
      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      # -----------------------------
      # Generate changelog
      # -----------------------------
      - name: Generate CHANGELOG.md
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          writeToFile: true
          tag: agent-desk-5.0.2

      # -----------------------------
      # Commit updated CHANGELOG.md
      # -----------------------------
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.ref_name }}
          commit_message: "docs: update CHANGELOG.md [skip ci]"
          file_pattern: CHANGELOG.md

      # -----------------------------
      # Release Helm charts
      # -----------------------------
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
